### ISSUE TITLE
gcp_disc_client.py creates GcpOrganization from "domain:" members without "name" property, leading to crashes

### ISSUE THREAD

**Issue by rf-mgb** [carlospolop/PurplePanda#32]
In gcp_disc_client.py, when gathering IAM policies in `get_iam_policy`, the following code creates a GcpOrganization without the name property:
```
                elif member.startswith("domain:"):
                    o_domain = member.replace("domain:", "")
                    m_obj: GcpOrganization = GcpOrganization(
                        domain = o_domain
                    ).save()
                    m_objs = [m_obj]
```

This makes PurplePanda (for GCP) crash when attempting to get the Org Policies for this GcpOrganization. Trace of the crash because the `name` property is missing:
```
Google disc_org_policies.orgs ━━━━━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━ 50.0% • 2 • 0:00:04 ⠋
Traceback (most recent call last):
  File "/opt/PurplePanda/main.py", line 216, in <module>
    main()
  File "/opt/PurplePanda/main.py", line 188, in main
    PurplePanda().start_discovery(functions)
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 197, in start_discovery
    t.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/purplepanda_google.py", line 80, in discover
    ).do_discovery()
      ^^^^^^^^^^^^^^
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 17, in do_discovery
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 17, in do_discovery
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 56, in discover
    self._disc()
  File "/opt/PurplePanda/intel/google/discovery/disc_org_policies.py", line 28, in _disc
    self._disc_loop(orgs, self._disc_org_policies, __name__.split(".")[-1]+".orgs")
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 68, in _disc_loop
    func(item, **kwargs) # Here the keyworded arguments are being passed to the function
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/discovery/disc_org_policies.py", line 40, in _disc_org_policies
    prep_http = self.service.organizations().listOrgPolicies(resource=org_obj.name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/lib/python3.11/site-packages/googleapiclient/discovery.py", line 1114, in method
    raise TypeError('Missing required parameter "%s"' % name)
TypeError: Missing required parameter "resource"
```

The main issue hence seems to be that disc_org_policies.py expects the `name` property to be populated, but because the GcpOrganization was instantiated without the `name` property, it is not present:
```
    def _disc_org_policies(self, org_obj:GcpOrganization):
        """Discover each policy of the organization"""

        prep_http = self.service.organizations().listOrgPolicies(resource=org_obj.name)   # here the name is required but not present
        policies: List[str] = self.execute_http_req(prep_http, "policies")
        for policy in policies:
            self._save_policy(policy, org_obj)
```

I have a dirty hack to fix the issue for me.

In the case of our environment, the "domain:" member looks as follows: `<ORG-ID>-<RANDOM_STRING>.apps.googleusercontent.com`.

Hence I added the following patch to ` gcp_disc_client.py`:
```
--- a/intel/google/discovery/gcp_disc_client.py
+++ b/intel/google/discovery/gcp_disc_client.py
@@ -270,10 +270,17 @@ class GcpDiscClient(PurplePanda):
                 
                 elif member.startswith("domain:"):
                     o_domain = member.replace("domain:", "")
+                    if "apps.googleusercontent.com" in o_domain:
+                        o_name = "organizations/" + o_domain.split("-")[0]
+                    else:
+                        o_name = "organizations/" + o_domain
                     m_obj: GcpOrganization = GcpOrganization(
-                        domain = o_domain
+                        domain = o_domain,
+                        name = o_name
                     ).save()
                     m_objs = [m_obj]
+                    print(f"IAM policy for {resource_name}:")
+                    print(f"Role: {role_name}, member: {member}")
                 
                 elif member == "allUsers":
                     m_obj: GcpUserAccount = GcpUserAccount(
```

This quick and dirty patch only constructs the `name` property correctly for cases where the domain follows the above format ( `<ORG-ID>-<RANDOM_STRING>.apps.googleusercontent.com`). As I have no patch that would work for other domain formats too I have no PR request at this time but wanted to report the bug nonetheless.

**Comment by carlospolop** [comment]
Thanks! I'll keep this in mind in case I find an environment with this error where I can see how to properly fix it

**Comment by carlospolop** [comment]
I have applied your patch, lets see how it performs
