### ISSUE TITLE
GCP: Method _disc_sas in disc_sa.py crashes when processing keys missing keyAlgorithm dict key (e.g. keys with 'keyOrigin'='USER_PROVIDED')

### ISSUE THREAD

**Issue by rf-mgb** [carlospolop/PurplePanda#33]
In the method `_disc_sas` in the file `disc_sa.py`, GcpApiKey objects are constructed:

```
    def _disc_sas(self, p_obj:GcpProject):
        """Discover all the service accounts of a project"""

        project_name: str = p_obj.name
        http_prep = self.service.projects().serviceAccounts()#.list(name=project_name)
        accounts: List[str] = self.execute_http_req(http_prep, "accounts", disable_warn=True, list_kwargs={"name": project_name})
        for sa in accounts:
            sa_name = sa["name"]

            sa_obj = GcpServiceAccount(
                name = sa_name,
                uniqueId = sa["uniqueId"],
                email = sa["email"],
                displayName = sa.get("displayName", ""),
                description = sa.get("description", "")
            ).save()
            sa_obj.projects.update(p_obj)
            sa_obj.save()

            http_prep = self.service.projects().serviceAccounts().keys()#.list(name=sa_name)
            keys: List[str] = self.execute_http_req(http_prep, "keys", list_kwargs={"name": sa_name})
            for key in keys:
                if key["keyOrigin"] != "USER_PROVIDED":
                    api_key_obj: GcpApiKey = GcpApiKey(
                        name=key["name"],
                        validAfterTime=key["validAfterTime"],
                        validBeforeTime=key["validBeforeTime"],
                        keyAlgorithm=key["keyAlgorithm"],
                        keyOrigin=key["keyOrigin"],
                        keyType=key["keyType"],
                    )
                    api_key_obj.service_accounts.update(sa_obj)
                    api_key_obj.save()

            self.get_iam_policy(sa_obj, self.service.projects().serviceAccounts(), sa_obj.name)
```

This method crashes when trying to instantiate a `GcpApiKey` when that key has no `keyAlgorithm` attribute. Example trace:

```
Traceback (most recent call last):
  File "/opt/PurplePanda/main.py", line 216, in <module>
    main()
  File "/opt/PurplePanda/main.py", line 188, in main
    PurplePanda().start_discovery(functions)
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 197, in start_discovery
    t.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/purplepanda_google.py", line 80, in discover
    ).do_discovery()
      ^^^^^^^^^^^^^^
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 17, in do_discovery
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 17, in do_discovery
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 56, in discover
    self._disc()
  File "/opt/PurplePanda/intel/google/discovery/disc_sa.py", line 24, in _disc
    self._disc_loop(projects, self._disc_sas, __name__.split(".")[-1]+"._disc_sas")
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 68, in _disc_loop
    func(item, **kwargs) # Here the keyworded arguments are being passed to the function
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/discovery/disc_sa.py", line 57, in _disc_sas
    keyAlgorithm=key["keyAlgorithm"],
                 ~~~^^^^^^^^^^^^^^^^
KeyError: 'keyAlgorithm'
```

This seems to happen with some keys that do not have a keyAlgorithm set. For example, the following key which has `'keyOrigin': 'USER_PROVIDED'`. In this case, there is no `keyAlgorithm` key/value pair in the dict:
`{'name': 
'projects/<CENSORED>/serviceAccounts/<CENSORED>@<CENSORED>.iam.gserviceaccount.com/keys/<CENSORED>', 
'validAfterTime': '2023-12-11T13:40:19Z', 'validBeforeTime': '2024-12-10T13:40:19Z', 'keyOrigin': 'USER_PROVIDED', 'keyType': 'USER_MANAGED'}`

A potential fix could be:

1. Check if the keyAlgorithm key exists in the key dict
2. If it exists, use its value when instantiating the `GcpApiKey` object (`keyAlgorithm=key["keyAlgorithm"]`)
3. If the key does not exist, use the empty string `""` when instantiating the  `GcpApiKey` object (`keyAlgorithm=""`)

**Comment by carlospolop** [comment]
Hi @rf-mgb thanks for reporting this bug! I just merged a fix
