### ISSUE TITLE
K8sIngress missing public_ips, leading to crashes during disc_ingresses.py

### ISSUE THREAD

**Issue by rf-mgb** [carlospolop/PurplePanda#35]
In the method _save_ingress(...), public IP addresses can be sved for a K8sIngress:

```
    def _save_ingress(self, ingress, **kwargs):
        """Given K8s ingress information, save it"""

        ns_obj = kwargs["ns_obj"]
        ns_name = ns_obj.name
        ingress_obj = K8sIngress(
            name = f"{ns_name}:{ingress.metadata.name}",
            self_link = ingress.metadata.self_link,
            uid = ingress.metadata.uid,
            labels = json.dumps(ingress.metadata.labels),
        ).save()
        ingress_obj.namespaces.update(ns_obj)
        ingress_obj.save()
        
<CUT FOR BREVITY>
        
        if ingress.status and ingress.status.load_balancer and ingress.status.load_balancer.ingress:
            for info in ingress.status.load_balancer.ingress:
                ip = info.ip
                if ip:
                    ip_obj = PublicIP(name=ip).save()
                    ingress_obj.public_ips.update(ip_obj)
```

However, the model is missing the relationship:

```
class K8sIngress(K8sBasicModelNS):
    __primarylabel__ = "K8sIngress"
    __primarykey__ = "name"

    public_domains = RelatedTo(PublicDomain, "HAS_DOMAIN")
    services = RelatedTo(K8sService, "TO_SERVICE")
    secrets = RelatedTo("K8sSecret", "USE_SECRET")

    k8s = Label(name="K8s")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
```

This leads to crashes:

```
   K8s disc_ingresses      ━━━━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━ 41.2% • 17  • 0:00:02 ⠴
   K8s disc_ingresses-kong ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0%  • 4   • 0:00:02 ⠴
Traceback (most recent call last):
  File "/opt/PurplePanda/main.py", line 216, in <module>
    main()
  File "/opt/PurplePanda/main.py", line 188, in main
    PurplePanda().start_discovery(functions)
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 197, in start_discovery
    t.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/purplepanda_google.py", line 80, in discover
    ).do_discovery()
      ^^^^^^^^^^^^^^
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 17, in do_discovery
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 17, in do_discovery
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 56, in discover
    self._disc()
  File "/opt/PurplePanda/intel/google/discovery/disc_clusters.py", line 31, in _disc
    self._disc_loop(projects, self._disc_clusters, __name__.split(".")[-1])
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 68, in _disc_loop
    func(item, **kwargs) # Here the keyworded arguments are being passed to the function
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/discovery/disc_clusters.py", line 41, in _disc_clusters
    self.save_cluster(cluster, p_obj)
  File "/opt/PurplePanda/intel/google/discovery/disc_clusters.py", line 161, in save_cluster
    self.analyze_cluster(cluster_obj, p_obj)
  File "/opt/PurplePanda/intel/google/discovery/disc_clusters.py", line 224, in analyze_cluster
    self.start_discovery(functions)
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 197, in start_discovery
    t.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/k8s/purplepanda_k8s.py", line 91, in discover
    ).do_discovery()
      ^^^^^^^^^^^^^^
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 17, in do_discovery
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 34, in do_discovery
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 56, in discover
    self._disc()
  File "/opt/PurplePanda/intel/k8s/discovery/disc_ingresses.py", line 20, in _disc
    self._disc_loop(namespaces, self._disc_ingresses, __name__.split(".")[-1])
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 68, in _disc_loop
    func(item, **kwargs) # Here the keyworded arguments are being passed to the function
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/k8s/discovery/disc_ingresses.py", line 31, in _disc_ingresses
    self._disc_loop(ingresses.items, self._save_ingress, __name__.split(".")[-1]+f"-{ns_obj.ns_name}", **{"ns_obj": ns_obj})
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 68, in _disc_loop
    func(item, **kwargs) # Here the keyworded arguments are being passed to the function
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/k8s/discovery/disc_ingresses.py", line 80, in _save_ingress
    ingress_obj.public_ips.update(ip_obj)
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'K8sIngress' object has no attribute 'public_ips'
```

Likely solution: Add the relationship to the model in `k8s_model.py`, class `K8sIngress`:

```
class K8sIngress(K8sBasicModelNS):
    __primarylabel__ = "K8sIngress"
    __primarykey__ = "name"

    public_domains = RelatedTo(PublicDomain, "HAS_DOMAIN")
    services = RelatedTo(K8sService, "TO_SERVICE")
    secrets = RelatedTo("K8sSecret", "USE_SECRET")
    public_ips = RelatedTo(PublicIP, "HAS_IP")

    k8s = Label(name="K8s")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
```

**Comment by carlospolop** [comment]
Thanks @rf-mgb this should be fixed now!
