### ISSUE TITLE
GCP: DiscComputeInstances crashes in _disc_instances because KeyError: 'subnetwork'

### ISSUE THREAD

**Issue by rf-mgb** [carlospolop/PurplePanda#36]
The method `_disc_instances(...)` in the file `disc_compute_instances.py` can crash when instantiating a `GcpSubnetwork` object because the `subnetwork` does not exist on all `nic`s.

Crash trace:

```
Traceback (most recent call last):
  File "/opt/PurplePanda/main.py", line 216, in <module>
    main()
  File "/opt/PurplePanda/main.py", line 188, in main
    PurplePanda().start_discovery(functions)
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 197, in start_discovery
    t.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/purplepanda_google.py", line 80, in discover
    ).do_discovery()
      ^^^^^^^^^^^^^^
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 17, in do_discovery
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 27, in do_discovery
    t.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 39, in _do_parallel
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 56, in discover
    self._disc()
  File "/opt/PurplePanda/intel/google/discovery/disc_compute_instances.py", line 24, in _disc
    self._disc_loop(projects, self._disc_instances, __name__.split(".")[-1])
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 68, in _disc_loop
    func(item, **kwargs) # Here the keyworded arguments are being passed to the function
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/discovery/disc_compute_instances.py", line 105, in _disc_instances
    name = "projects/" + nic["subnetwork"].split("projects/")[1],
                         ~~~^^^^^^^^^^^^^^
KeyError: 'subnetwork'
```

Code that crashes (in current version the problem is in line 105):

```
subnet_obj: GcpSubnetwork = GcpSubnetwork(
    name = "projects/" + nic["subnetwork"].split("projects/")[1],
    selfLink = nic["subnetwork"]
).save()
```

Suggested solution: check if the NIC object has the `subnetwork` key before instantiating the `GcpSubnetwork` object.

For example, but currently untested:

```
--- a/intel/google/discovery/disc_compute_instances.py
+++ b/intel/google/discovery/disc_compute_instances.py
@@ -101,27 +101,29 @@ class DiscComputeInstances(GcpDisc):
                         natIps = [elem["natIP"] for elem in accessConfigs if "natIP" in elem]
                         natIps += [elem["externalIpv6"] for elem in accessConfigs if "externalIpv6" in elem and not elem["externalIpv6"] in natIps]
 
-                        subnet_obj: GcpSubnetwork = GcpSubnetwork(
-                            name = "projects/" + nic["subnetwork"].split("projects/")[1],
-                            selfLink = nic["subnetwork"]
-                        ).save()
+                        if "subnetwork" in nic.keys():
+                            subnet_obj: GcpSubnetwork = GcpSubnetwork(
+                                name = "projects/" + nic["subnetwork"].split("projects/")[1],
+                                selfLink = nic["subnetwork"]
+                            ).save()
 
                         accessConfigsv6 = nic.get("accessConfigs", [])
                         natIpsv6 = [elem["natIP"] for elem in accessConfigsv6 if "natIP" in elem]
                         natIpsv6 += [elem["externalIpv6"] for elem in accessConfigs if "externalIpv6" in elem and not elem["externalIpv6"] in natIpsv6]
                         
-                        subnet_obj.instances.update(inst_obj,
-                            name = nic["name"], 
-                            networkIP = nic.get("networkIP", ""),
-                            stackType = nic.get("stackType", ""),
-                            accessConfigs_types = [elem["type"] for elem in accessConfigs],
-                            accessConfigs_names = [elem["name"] for elem in accessConfigs],
-                            accessConfigs_natIPs = natIps,
-                            accessConfigsv6_types = [elem["type"] for elem in accessConfigsv6],
-                            accessConfigsv6_names = [elem["name"] for elem in accessConfigsv6],
-                            accessConfigsv6_natIPs = natIpsv6,
-                        )
-                        subnet_obj.save()
+                        if "subnetwork" in nic.keys():
+                            subnet_obj.instances.update(inst_obj,
+                                name = nic["name"], 
+                                networkIP = nic.get("networkIP", ""),
+                                stackType = nic.get("stackType", ""),
+                                accessConfigs_types = [elem["type"] for elem in accessConfigs],
+                                accessConfigs_names = [elem["name"] for elem in accessConfigs],
+                                accessConfigs_natIPs = natIps,
+                                accessConfigsv6_types = [elem["type"] for elem in accessConfigsv6],
+                                accessConfigsv6_names = [elem["name"] for elem in accessConfigsv6],
+                                accessConfigsv6_natIPs = natIpsv6,
+                            )
+                            subnet_obj.save()
```

**Comment by carlospolop** [comment]
fixed! Thanks for the bug @rf-mgb !
