### ISSUE TITLE
GCP: analyze_results.py crashes in _check_privesc_to_res because 'GcpBqTable' object has no attribute 'projects'

### ISSUE THREAD

**Issue by rf-mgb** [carlospolop/PurplePanda#37]
After data collection, during the analysis phase, the method `_check_privesc_to_res` in the file `analyze_results.py` crashes because it expects there to be a `projects` attribute on `GcpBqTable` objects but it does not exist.

Crash trace:
```
Traceback (most recent call last):
  File "/opt/PurplePanda/main.py", line 216, in <module>
    main()
  File "/opt/PurplePanda/main.py", line 188, in main
    PurplePanda().start_discovery(functions)
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 197, in start_discovery
    t.result()
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/purplepanda_google.py", line 80, in discover
    ).do_discovery()
      ^^^^^^^^^^^^^^
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 34, in do_discovery
    self._call_f(f)
  File "/opt/PurplePanda/core/utils/discover_saas.py", line 44, in _call_f
    func()
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 56, in discover
    self._disc()
  File "/opt/PurplePanda/intel/google/discovery/analyze_results.py", line 33, in _disc
    self._disc_loop(privesc_data, self._disc_privesc_technique, __name__.split(".")[-1])
  File "/opt/PurplePanda/core/utils/purplepanda.py", line 68, in _disc_loop
    func(item, **kwargs) # Here the keyworded arguments are being passed to the function
    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/discovery/analyze_results.py", line 67, in _disc_privesc_technique
    ppals_rscs = self._get_principals_with_role(role, only_to_classes, extra_privesc_to, running_in, second_order_relations)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/discovery/analyze_results.py", line 223, in _get_principals_with_role
    resources = self._get_assets_from_principal_with_role(ppal, role, only_to_classes, extra_privesc_to, running_in, second_order_relations)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/discovery/analyze_results.py", line 294, in _get_assets_from_principal_with_role
    resources += self._get_recursive_resources(resource, resources_already, only_to_classes, 
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/discovery/analyze_results.py", line 330, in _get_recursive_resources
    res = self._check_privesc_to_res(res, extra_privesc_to) #returned res COULD be a list!
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/PurplePanda/intel/google/discovery/analyze_results.py", line 378, in _check_privesc_to_res
    for obj2, _ in res.projects._related_objects:
                   ^^^^^^^^^^^^
AttributeError: 'GcpBqTable' object has no attribute 'projects'
```

The following code shows that the `projects` attribute is not present on `GcpBqTable` objects:
```
class GcpBqTable(GcpResource):
    __primarylabel__ = "GcpBqTable"
    __primarykey__ = "name"

    name = Property() # project-name:datasetname.table name
    tableId = Property() # table name
    type = Property() # 'TABLE'
    resource_name = Property()

    bgdatasets = RelatedTo(GcpBqDataset, "PART_OF")

    gcp = Label(name="Gcp")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.gcp = True
```

The following code is the crash location:

```
    def _check_privesc_to_res(self, res:CustomOGM, extra_privesc_to):
        """Given a resource, check if it's inside the scope to privesc or get the obj where it should privesc"""
        
        obj = None
        # Check if you should escalate to all project SAs
        if extra_privesc_to == "ALL_PROJECT_SAS":
            for obj2, _ in res.projects._related_objects:  # <-- this is the crash site
                if type(obj2) is GcpProject:
                    obj = obj2

        # Or just to the running SA in the resource
        elif extra_privesc_to == "RUNNING_SA":
            for obj2 in res.get_by_relation("RUN_IN"):
                obj = obj2
```

There are four possible solutions:

1. In the case of `GcpBqTable`, perform no privilege escalation checks
2. In the case of `GcpBqTable`, check by going up the chain and check if the associated `GcpBqDataset` is prone to privilege escalation
3. Save the `projects` property also for `GcpBqTable` objects
4. For all `res` objects passed into `_check_privesc_to_res`, test if they have the `projects` attribute

Suggested solution for option 4 - not yet tested:

```
--- a/intel/google/discovery/analyze_results.py
+++ b/intel/google/discovery/analyze_results.py
@@ -375,9 +375,10 @@ class AnalyzeResults(GcpDisc):
         obj = None
         # Check if you should escalate to all project SAs
         if extra_privesc_to == "ALL_PROJECT_SAS":
-            for obj2, _ in res.projects._related_objects:
-                if type(obj2) is GcpProject:
-                    obj = obj2
+            if hasattr(res, "projects"):
+                for obj2, _ in res.projects._related_objects:
+                    if type(obj2) is GcpProject:
+                        obj = obj2
 
         # Or just to the running SA in the resource
         elif extra_privesc_to == "RUNNING_SA":
```

**Comment by carlospolop** [comment]
I have added the `projects` relation to BQ, hopefully this should be enough, but let me know if you find the issue again
